version: 2.1

orbs:
  gem: goldstar/publish-gem@1.0.1

workflows:
  main:
    jobs:
      - test
      - gem/build-and-deploy:
          context: packagecloud
          requires:
            - test
          filters:
            branches:
              only: master
          packagecloud-repo: goldstar/production

jobs:
  test:
    docker:
      # specify the version you desire here
       - image: circleci/ruby:2.5.5-node-browsers

    working_directory: ~/goldstar/hide_and_seek

    steps:
      - checkout
      - restore_cache:
          keys:
          - hide-and-seek-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - hide-and-seek-

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          key: hide-and-seek-{{ checksum "Gemfile.lock" }}
          paths:
            - ./vendor/bundle

      # run tests!
      - run: bundle exec rspec spec

      - store_test_results:
          path: /tmp/circleci-test-results
      - store_artifacts:
          path: /tmp/circleci-artifacts
      - store_artifacts:
          path: /tmp/circleci-test-results
